"""
Django settings for G_Project project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = open('.secret', 'r').read()

# SECURITY WARNING: don't run with debug turned on in production!
if os.name == 'nt':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",

    # 로그인 관련
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "G_Project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "G_Project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'g_project',
        'USER': 'root',
        'PASSWORD': '1234qwer',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# AUTH_USER_MODEL = 'api.User'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "ko"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"


MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#간편 로그인 관련 설정

ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_ADAPTER_CLASS = 'G_Project.core.adapter.MyAccountAdapter'

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'

SOCIAL_PROVIDERS = {
    'naver': {
        'APP': {
            'client_id': '9VonWGGFfdKrpns5cxOR',
            'secret': 'fXkqGIKzKh',
        }
    },
    'kakao': {
        'APP': {
            'client_id': '2d9a8c40a0e8c3ffc616db53634327fb',
            'secret': 'KAKAO_SECRET_KEY',
        }
    }

}
SOCIALACCOUNT_PROVIDERS = {
    'naver': {
        'APP': {
            'client_id': '9VonWGGFfdKrpns5cxOR',
            'secret': 'fXkqGIKzKh',
            'key': '',
        },
        # 'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        # 'METHOD': 'oauth2',
        # 'VERIFIED_EMAIL': False,
        # 'ID_KEY': '9VonWGGFfdKrpns5cxOR',
        # 'SECRET_KEY': 'fXkqGIKzKh',
    },
    'kakao': {
        'APP': {
            'client_id': '2d9a8c40a0e8c3ffc616db53634327fb',
            'secret': 'KAKAO_SECRET_KEY',
            'key': '',
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': False,
        'ID_KEY': 'id',
        'SECRET_KEY': 'KAKAO_SECRET_KEY',
    },
    # 'apple': {
    #     'APP': {
    #         'client_id': 'APPLE_CLIENT_ID',
    #         'client_secret': 'APPLE_SECRET_KEY',
    #         'key': '',
    #     },
    #     'SCOPE': ['name', 'email'],
    #     'METHOD': 'jwt',
    #     'VERIFIED_EMAIL': True,
    #     'ID_KEY': 'sub',
    #     'SECRET_KEY': 'APPLE_SECRET_KEY',
    # },
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = 'sale_agent'
ACCOUNT_LOGOUT_REDIRECT_URL = 'product'
ACCOUNT_LOGOUT_ON_GET = True


